apiVersion: v1
kind: Service
metadata:
  name: product-service
  namespace: devops-poc
spec:
  type: ClusterIP
  selector:
    app: product-service
  ports:
    - port: 3002
      targetPort: 3002
      protocol: TCP
