apiVersion: v1
kind: Service
metadata:
  name: order-service
  namespace: devops-poc
spec:
  type: ClusterIP
  selector:
    app: order-service
  ports:
    - port: 3003
      targetPort: 3003
      protocol: TCP
